### PR TITLE
Bugfix/incorrect min max

### PR DESCRIPTION
**Pull request by yadue**
Min max options are working incorrectly: 

If I set

minDate -> 15.06.2021, then it allows to select 01.06-15.06. First argument should be date, not this.options.minDate. Same situation for maxDate.

```
  private isDateSelectable(date: Date): boolean {
    if (this.options.minDate && isBefore(this.options.minDate, date)) {
      return false;    
    }
    if (this.options.maxDate && isAfter(this.options.maxDate, date)) {
      return false;
    }
    return true;
  }
```

This PR fixes it.

### CODE REVIEW

**Review by jkuri — APPROVED** [review]
LGTM 👍  please sign CLA so I can merge this.

**Comment by jkuri** [comment]
and please keep `package-lock.json` file, also rebase against current master otherwise I cannot merge it.

**Comment by yadue** [comment]
@jkuri can you publish npm package? Thanks in advance

**Comment by jkuri** [comment]
@yadue already done.

**Pull request closed without merging**
