### PR TITLE
Added reset method to clear the date selection from the calendar modal.

### PR DESCRIPTION
**Pull request by pkhisticastlight**
Added reset method to clear the date selection from the calendar modal.
Please let me know if any other changes are needed, I will be happy to contribute.

### CODE REVIEW

**Comment by pkhisticastlight** [comment]
screen shot 2018-05-04 at 1 40 29 pm

**Comment by jkuri** [comment]
released on npm as `2.3.1`. thanks!

**Comment by anupbangale** [comment]
Is any one knows, what is the configuration we need to set in a **options** to have clear button in a date picker UI like enableClearButton: true or something like ?.

**Comment by kuldeeps1ngh** [comment]
You can easily clear selected date using ElementRef:

```
<ng-datepicker [(ngModel)]="empty_date" [options]="options1" #date1></ng-datepicker>  

<button (click)="date1.displayValue=''">Clear Date</button>
```

OR

You can clear it from component also:

```
@ViewChild('date1') date1: ElementRef;

resetDate() {
    this.date1['displayValue']='';
}
```

**Pull request merged**
