### PR TITLE
Add new attributes to the README

### PR DESCRIPTION
**Pull request by x1unix**
Syncing docs with recent changes from PR #273

### CODE REVIEW

**Comment by jkuri** [comment]
I believe you did not rebase correctly. 
```
git remote add upstream https://github.com/bleenco/ng2-datepicker.git
git fetch upstream
git rebase upstream/master
git push origin master -f
```

**Comment by x1unix** [comment]
@jkuri, I've used docs from GitHub - https://help.github.com/articles/syncing-a-fork/. But I'll try yours way.

**Comment by jkuri** [comment]
screen shot 2017-11-23 at 17 08 41
also if you do it via UI it adds some unnecessary commit like you see
`Merge remote-tracking branch 'upstream/master'` which is really not needed.

**Comment by x1unix** [comment]
@jkuri, try now

**Pull request merged**
