### PR TITLE
allows date picker to expand from the left

### PR DESCRIPTION
**Pull request by wickdninja**
I really like your datepicker 👍 to ionic and 👍 to you 😄!

However, to appease my designer I had to make the datepicker expand from the left as well as the right side, and I thought you may find this to be a useful addition. Thanks again.

### CODE REVIEW

**Comment by ghetolay** [comment]
I wouldn't vote for this PR. I think the real problem here is about customization of css.

Do you need to change the expand size during the lifetime of the component ? Or is it just a setup configuration ?

**Comment by wickdninja** [comment]
Setup config. I also solved via CSS, but our team liked the attribute binding.

**Comment by x1unix** [comment]
@wickdninja, already implemented. Use `[position]` attribute.

**Comment by wickdninja** [comment]
Thanks closing

**Comment by vkumar342** [comment]
position: attribute is not working.

**Pull request closed without merging**
